// Server-only answer key for Battle 3 multiple-choice challenges.
// This file is imported by the API route, never by the student client bundle.
export const BOARD_MCQ_ANSWERS: Record<string, string> = {
  R01: 'She was glad she changed her plan.',
  R03: 'To show evidence of the guitar’s condition.',
  R04: 'Donations should still be safe to use.',
  R06: 'She wanted to avoid the busiest time.',
  R07: 'Practice will still take place if it rains.',
  R09: 'The poster has to be ready before recess.',
  R11: 'Frustrated by the delay.',
  R12: 'She received guidance and tried again.',
  R14: 'Bring a suitable used book.',
  R16: 'To stop the pots from falling or being damaged.',
  R17: 'Clear visual labels on the bins.',
  G01: 'had',
  G02: 'were waiting',
  G04: 'much',
  G05: 'since',
  G07: 'should',
  G08: 'the',
  G10: 'are',
  G11: 'was completed',
  G13: 'because',
  G14: 'a few',
  G16: 'had opened',
  G17: 'whose',
  G19: 'onto',
  G20: 'in',
  G22: 'but',
  G23: 'She gave me a useful tip.',
  V01: 'check',
  V02: 'slippery',
  V03: 'delighted',
  V04: 'clear',
  V05: 'cancel',
  V06: 'take care of',
  V07: 'clearly',
  V08: 'full of people',
  V09: 'come up with',
  V10: 'detailed',
  V11: 'make',
  V12: 'pay',
  V13: 'can be trusted',
  V14: 'exhausted',
  V15: 'note down',
};
